import antfu from '@antfu/eslint-config'

export default antfu({
  vue: true,
  rules: {
    'no-console': 'warn',
    'curly': ['error', 'multi-line', 'consistent'],
  },
  ignores: [
    //  Generated by Cargo
    // will have compiled files and executables
    'src-tauri/target/*',

    //  Generated by Tauri
    //  will have schema files for capabilities auto-completion
    'src-tauri/gen/schemas',
  ],
})
